# Generated by Django 3.2.9 on 2021-11-16 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='extendedusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('personal', 'PERSONAL'), ('ngo', 'NGO')], default='PERSONAL', max_length=50)),
                ('city', models.CharField(choices=[('indore', 'INDORE'), ('dewas', 'DEWAS'), ('mhow', 'MHOW'), ('rao', 'RAO'), ('bhopal', 'BHOPAL'), ('ujjain', 'UJJAIN')], default='INDORE', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
