# Generated by Django 3.2.9 on 2021-11-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('ujjain', 'UJJAIN'), ('bhopal', 'BHOPAL'), ('dewas', 'DEWAS'), ('indore', 'INDORE'), ('rao', 'RAO'), ('mhow', 'MHOW')], default='INDORE', max_length=50),
        ),
    ]
