# Generated by Django 3.2.9 on 2021-11-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0003_auto_20211116_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('bhopal', 'BHOPAL'), ('ujjain', 'UJJAIN'), ('mhow', 'MHOW'), ('indore', 'INDORE'), ('dewas', 'DEWAS'), ('rao', 'RAO')], default='INDORE', max_length=50),
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='userType',
            field=models.CharField(choices=[('personal', 'PERSONAL'), ('ngo', 'NGO')], default='PERSONAL', max_length=50),
        ),
    ]
