# Generated by Django 3.2.9 on 2021-11-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0004_auto_20211116_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('indore', 'INDORE'), ('bhopal', 'BHOPAL'), ('mhow', 'MHOW'), ('ujjain', 'UJJAIN'), ('rao', 'RAO'), ('dewas', 'DEWAS')], default='INDORE', max_length=50),
        ),
    ]
