# Generated by Django 3.2.9 on 2021-11-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0005_alter_extendedusers_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('bhopal', 'BHOPAL'), ('rao', 'RAO'), ('ujjain', 'UJJAIN'), ('dewas', 'DEWAS'), ('mhow', 'MHOW'), ('indore', 'INDORE')], default='INDORE', max_length=50),
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='userType',
            field=models.CharField(choices=[('ngo', 'NGO'), ('personal', 'PERSONAL')], default='PERSONAL', max_length=50),
        ),
    ]
