# Generated by Django 3.2.9 on 2021-11-26 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FoodDonation', '0006_auto_20211116_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('dewas', 'DEWAS'), ('mhow', 'MHOW'), ('rao', 'RAO'), ('indore', 'INDORE'), ('bhopal', 'BHOPAL'), ('ujjain', 'UJJAIN')], default='INDORE', max_length=50),
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='userType',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='extendedNgoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pinCode', models.CharField(max_length=10)),
                ('otherDetails', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
