# Generated by Django 3.2.9 on 2021-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0007_auto_20211126_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedngorequest',
            name='ngo_id',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('rao', 'RAO'), ('ujjain', 'UJJAIN'), ('mhow', 'MHOW'), ('dewas', 'DEWAS'), ('indore', 'INDORE'), ('bhopal', 'BHOPAL')], default='INDORE', max_length=50),
        ),
    ]
