# Generated by Django 3.2.9 on 2021-11-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0008_auto_20211126_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedngorequest',
            name='otherDetails',
        ),
        migrations.AddField(
            model_name='extendedngorequest',
            name='contactNumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('indore', 'INDORE'), ('ujjain', 'UJJAIN'), ('bhopal', 'BHOPAL'), ('mhow', 'MHOW'), ('dewas', 'DEWAS'), ('rao', 'RAO')], default='INDORE', max_length=50),
        ),
    ]
