# Generated by Django 3.2.9 on 2021-11-28 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FoodDonation', '0009_auto_20211128_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedngorequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('rao', 'RAO'), ('ujjain', 'UJJAIN'), ('bhopal', 'BHOPAL'), ('indore', 'INDORE'), ('dewas', 'DEWAS'), ('mhow', 'MHOW')], default='INDORE', max_length=50),
        ),
    ]
