# Generated by Django 3.2.9 on 2021-11-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0010_auto_20211128_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedngorequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('bhopal', 'BHOPAL'), ('ujjain', 'UJJAIN'), ('indore', 'INDORE'), ('dewas', 'DEWAS'), ('rao', 'RAO'), ('mhow', 'MHOW')], default='INDORE', max_length=50),
        ),
    ]
