# Generated by Django 3.2.9 on 2021-11-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0011_auto_20211129_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('ujjain', 'UJJAIN'), ('dewas', 'DEWAS'), ('rao', 'RAO'), ('bhopal', 'BHOPAL'), ('mhow', 'MHOW'), ('indore', 'INDORE')], default='INDORE', max_length=50),
        ),
    ]
