# Generated by Django 3.2.9 on 2021-11-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0012_alter_extendedusers_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('rao', 'RAO'), ('bhopal', 'BHOPAL'), ('indore', 'INDORE'), ('mhow', 'MHOW'), ('dewas', 'DEWAS'), ('ujjain', 'UJJAIN')], default='INDORE', max_length=50),
        ),
    ]
