# Generated by Django 3.2.9 on 2021-11-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0013_alter_extendedusers_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('bhopal', 'BHOPAL'), ('mhow', 'MHOW'), ('indore', 'INDORE'), ('rao', 'RAO'), ('ujjain', 'UJJAIN'), ('dewas', 'DEWAS')], default='INDORE', max_length=50),
        ),
    ]
