# Generated by Django 3.2.9 on 2021-11-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0014_alter_extendedusers_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendedNgoAcceptedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pinCode', models.CharField(max_length=10)),
                ('contactNumber', models.CharField(default='', max_length=10)),
                ('ngo_id', models.CharField(default='', max_length=4)),
                ('request_id', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('bhopal', 'BHOPAL'), ('rao', 'RAO'), ('mhow', 'MHOW'), ('dewas', 'DEWAS'), ('indore', 'INDORE'), ('ujjain', 'UJJAIN')], default='INDORE', max_length=50),
        ),
    ]
