# Generated by Django 3.2.9 on 2021-12-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0015_auto_20211130_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedngoacceptedrequest',
            name='request_date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='extendedngorequest',
            name='request_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('indore', 'INDORE'), ('mhow', 'MHOW'), ('bhopal', 'BHOPAL'), ('dewas', 'DEWAS'), ('ujjain', 'UJJAIN'), ('rao', 'RAO')], default='INDORE', max_length=50),
        ),
    ]
