# Generated by Django 3.2.9 on 2021-12-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0016_auto_20211201_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedngoacceptedrequest',
            name='request_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extendedngorequest',
            name='request_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('mhow', 'MHOW'), ('ujjain', 'UJJAIN'), ('indore', 'INDORE'), ('dewas', 'DEWAS'), ('bhopal', 'BHOPAL'), ('rao', 'RAO')], default='INDORE', max_length=50),
        ),
    ]
