# Generated by Django 3.2.9 on 2021-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0017_auto_20211201_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedngoacceptedrequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='extendedngorequest',
            name='request_date',
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('mhow', 'MHOW'), ('bhopal', 'BHOPAL'), ('dewas', 'DEWAS'), ('indore', 'INDORE'), ('rao', 'RAO'), ('ujjain', 'UJJAIN')], default='INDORE', max_length=50),
        ),
    ]
