# Generated by Django 3.2.9 on 2021-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0018_auto_20211201_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('indore', 'INDORE'), ('bhopal', 'BHOPAL'), ('ujjain', 'UJJAIN'), ('rao', 'RAO'), ('dewas', 'DEWAS'), ('mhow', 'MHOW')], default='INDORE', max_length=50),
        ),
    ]
