# Generated by Django 3.2.9 on 2021-12-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonation', '0019_alter_extendedusers_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusers',
            name='city',
            field=models.CharField(choices=[('bhopal', 'BHOPAL'), ('dewas', 'DEWAS'), ('indore', 'INDORE'), ('mhow', 'MHOW'), ('rao', 'RAO'), ('ujjain', 'UJJAIN')], default='INDORE', max_length=50),
        ),
    ]
